version: '3.8'
services:
  api:
    container_name: 'musicpad-api'
    build: .
    env_file: '.env'
    ports:
      - 3080:3080
    links:
      - mongo
  mongo:
    container_name: 'mpdb'
    image: mongo
    ports:
      - 27017:27017